// Datos de prueba para desarrollo — reemplazar con llamadas reales al API

export const DEPENDENCIAS = [
  { id:   1, nombre: 'RECTORIA', codigo: 'REC', color: '', activo: true },
  { id:   2, nombre: 'VICE ADMVA', codigo: 'VA', color: '', activo: true },
  { id:   3, nombre: 'VICE DOCENTE', codigo: 'VD', color: '', activo: true },
  { id:   4, nombre: 'VICE POSTGRADO', codigo: 'VP', color: '', activo: true },
  { id:   5, nombre: 'VICE EXTENSION', codigo: 'VE', color: '', activo: true },
  { id:   6, nombre: 'SECRETARIA GRAL', codigo: 'SG', color: '', activo: true },
  { id:   7, nombre: 'MEDICINA', codigo: 'MED', color: '', activo: true },
  { id:   8, nombre: 'FAC. CIENCIAS', codigo: 'FC', color: '', activo: true },
  { id:   9, nombre: 'FAC. HUMANIDADES', codigo: 'FH', color: '', activo: true },
  { id:  10, nombre: 'FAC. ECONOMIA', codigo: 'FE', color: '', activo: true },
  { id:  11, nombre: 'FAC. INGENIERIA', codigo: 'FI', color: '', activo: true },
  { id:  12, nombre: 'FAC. EDUCACION', codigo: 'FE2', color: '', activo: true },
  { id:  13, nombre: 'FAC. CS JURIDICAS', codigo: 'FCJ', color: '', activo: true },
  { id:  14, nombre: 'FAC. ARTES', codigo: 'FA', color: '', activo: true },
  { id:  15, nombre: 'TESORERIA', codigo: 'TES', color: '', activo: true },
  { id:  16, nombre: 'DECANATO AGROVET', codigo: 'DA', color: '', activo: true },
  { id:  17, nombre: 'RECURSOS HUMANOS', codigo: 'RH', color: '', activo: true },
  { id:  18, nombre: 'CONTRALORIA', codigo: 'CON', color: '', activo: true },
  { id:  19, nombre: 'ASODEMU', codigo: 'ASO', color: '', activo: true },
  { id:  20, nombre: 'AUDITORIA GENERAL', codigo: 'AG', color: '', activo: true },
  { id:  21, nombre: 'SEGURIDAD', codigo: 'SEG', color: '', activo: true },
  { id:  22, nombre: 'FED', codigo: 'FED', color: '', activo: true },
  { id:  23, nombre: 'SUMINISTRO', codigo: 'SUM', color: '', activo: true },
  { id:  24, nombre: 'ECONOMATO', codigo: 'ECO', color: '', activo: true },
  { id:  25, nombre: 'UASD MAO', codigo: 'UM', color: '', activo: true },
  { id:  26, nombre: 'TALLER MECANICA', codigo: 'TM', color: '', activo: true },
  { id:  27, nombre: 'UASD PUERTO PLATA', codigo: 'UPP', color: '', activo: true },
  { id:  28, nombre: 'TRANSPORTACION', codigo: 'TRA', color: '', activo: true },
  { id:  29, nombre: 'TRANSITO', codigo: 'TRA2', color: '', activo: true },
  { id:  30, nombre: 'LABO-UASD', codigo: 'LU', color: '', activo: true },
  { id:  31, nombre: 'ESC. SALUD PUBLICA', codigo: 'ESP', color: '', activo: true },
  { id:  32, nombre: 'INMOBILIARIA', codigo: 'INM', color: '', activo: true },
  { id:  33, nombre: 'UASD LA VEGA', codigo: 'ULV', color: '', activo: true },
  { id:  34, nombre: 'MAYORDOMIA', codigo: 'MAY', color: '', activo: true },
  { id:  35, nombre: 'SOLIDARIDAD Y ESPERANZA', codigo: 'SYE', color: '', activo: true },
  { id:  36, nombre: 'ADMISIONES', codigo: 'ADM', color: '', activo: true },
  { id:  37, nombre: 'PLANTA FISICA', codigo: 'PF', color: '', activo: true },
  { id:  38, nombre: 'FAPROUASD', codigo: 'FAP', color: '', activo: true },
  { id:  39, nombre: 'UASD SANTO DOMINGO NORTE', codigo: 'USDN', color: '', activo: true },
  { id:  40, nombre: 'CONTRALORIA ADMINISTRATIVA', codigo: 'CA', color: '', activo: true },
  { id:  41, nombre: 'ORNATO', codigo: 'ORN', color: '', activo: true },
  { id:  42, nombre: 'FAC. AGRONOMIA', codigo: 'FA2', color: '', activo: true },
  { id:  43, nombre: 'UASD SANTIAGO', codigo: 'US', color: '', activo: true },
  { id:  44, nombre: 'UASD NEYBA', codigo: 'UN', color: '', activo: true },
  { id:  45, nombre: 'RESIDENCIAS MEDICAS', codigo: 'RM', color: '', activo: true },
  { id:  46, nombre: 'COMEDOR', codigo: 'COM', color: '', activo: true },
  { id:  47, nombre: 'PLAN DE RETIRO', codigo: 'PDR', color: '', activo: true },
  { id:  48, nombre: 'FAC. CS DE LA SALUD', codigo: 'FCDLS', color: '', activo: true },
  { id:  49, nombre: 'UASD SANTO DOMINGO ESTE', codigo: 'USDE', color: '', activo: true },
  { id:  50, nombre: 'ESC. DE ENFERMERIA', codigo: 'EDE', color: '', activo: true },
  { id:  51, nombre: 'UASD SAN FRANCISCO DE MACORIS', codigo: 'USFDM', color: '', activo: true },
  { id:  52, nombre: 'INST. GEOGRAFICO', codigo: 'IG', color: '', activo: true },
  { id:  53, nombre: 'UASD BANI', codigo: 'UB', color: '', activo: true },
  { id:  54, nombre: 'AGROVET', codigo: 'AGR', color: '', activo: true },
  { id:  55, nombre: 'INFORMATICA', codigo: 'INF', color: '', activo: true },
  { id:  56, nombre: 'UASD BARAHONA', codigo: 'UB2', color: '', activo: true },
  { id:  57, nombre: 'UASD NAGUA', codigo: 'UN2', color: '', activo: true },
  { id:  58, nombre: 'PRESUPUESTO', codigo: 'PRE', color: '', activo: true },
  { id:  59, nombre: 'UASD SFM', codigo: 'US2', color: '', activo: true },
  { id:  60, nombre: 'UASD HIGUEY', codigo: 'UH', color: '', activo: true },
  { id:  61, nombre: 'PROTOCOLO', codigo: 'PRO', color: '', activo: true },
  { id:  62, nombre: 'UASD SAN PEDRO DE MACORIS', codigo: 'USPDM', color: '', activo: true },
  { id:  63, nombre: 'FINCA', codigo: 'FIN', color: '', activo: true },
  { id:  64, nombre: 'BIENESTAR ESTUDIANTIL', codigo: 'BE', color: '', activo: true },
  { id:  65, nombre: 'SIERRA PRIETA', codigo: 'SP', color: '', activo: true },
  { id:  66, nombre: 'AUDIOVISUAL', codigo: 'AUD', color: '', activo: true },
  { id:  67, nombre: 'RESIDENCIA ESTUDIANTIL', codigo: 'RE', color: '', activo: true },
  { id:  68, nombre: 'CENTROS REGIONALES', codigo: 'CR', color: '', activo: true },
  { id:  69, nombre: 'UASD SANTO DOMINGO OESTE', codigo: 'USDO', color: '', activo: true },
  { id:  70, nombre: 'UASD BONAO', codigo: 'UB3', color: '', activo: true },
  { id:  71, nombre: 'UASD SAN CRISTOBAL', codigo: 'USC', color: '', activo: true },
  { id:  72, nombre: 'SECRETARIA', codigo: 'SEC', color: '', activo: true },
  { id:  73, nombre: 'RIESGOS Y DESASTRES', codigo: 'RYD', color: '', activo: true },
  { id:  74, nombre: 'UASD SANTIAGO RODRIGUEZ', codigo: 'USR', color: '', activo: true },
  { id:  75, nombre: 'CASA RECTOR/P. PLATA', codigo: 'CRP', color: '', activo: true },
  { id:  76, nombre: 'UASD SAN JUAN', codigo: 'USJ', color: '', activo: true },
  { id:  77, nombre: 'UASD HATO MAYOR', codigo: 'UHM', color: '', activo: true },
  { id:  78, nombre: 'DIR. GRAL. COMUNICACIONES', codigo: 'DGC', color: '', activo: true },
  { id:  79, nombre: 'COMPRAS', codigo: 'COM2', color: '', activo: true },
  { id:  80, nombre: 'GERENCIA FINANCIERA', codigo: 'GF', color: '', activo: true },
  { id:  81, nombre: 'RED DE CAFETERIAS', codigo: 'RDC', color: '', activo: true },
  { id:  82, nombre: 'ARS UASD', codigo: 'AU', color: '', activo: true },
  { id:  83, nombre: 'INST. SISMOLOGICO', codigo: 'IS', color: '', activo: true },
  { id:  84, nombre: 'VETERINARIA', codigo: 'VET', color: '', activo: true },
  { id:  85, nombre: 'COOPERACION INTERNACIONAL', codigo: 'CI', color: '', activo: true },
  { id:  86, nombre: 'CONSULTORIA JURIDICA', codigo: 'CJ', color: '', activo: true },
  { id:  87, nombre: 'DIR. GRAL. POSTGRADO', codigo: 'DGP', color: '', activo: true },
  { id:  88, nombre: 'RELACIONES PUBLICAS', codigo: 'RP', color: '', activo: true },
  { id:  89, nombre: 'DIGEPLANDI', codigo: 'DIG', color: '', activo: true },
]

export const PRODUCTOS = [
  { id: 1, nombre: 'Gasolina Regular',    categoria: 'combustible',        unidad: 'galones', stock_actual: 450,  stock_minimo: 100, precio_unitario: 280 },
  { id: 2, nombre: 'Gasoil',              categoria: 'combustible',        unidad: 'galones', stock_actual: 80,   stock_minimo: 100, precio_unitario: 260 },
  { id: 3, nombre: 'Aceite Motor 20W-50', categoria: 'aceite_motor',       unidad: 'cuartos', stock_actual: 120,  stock_minimo: 50,  precio_unitario: 350 },
  { id: 4, nombre: 'Aceite Motor 10W-30', categoria: 'aceite_motor',       unidad: 'cuartos', stock_actual: 45,   stock_minimo: 50,  precio_unitario: 380 },
  { id: 5, nombre: 'Aceite Transmision',  categoria: 'aceite_transmision', unidad: 'cuartos', stock_actual: 30,   stock_minimo: 20,  precio_unitario: 420 },
  { id: 6, nombre: 'Filtro de Aceite',    categoria: 'repuesto',           unidad: 'unidad',  stock_actual: 25,   stock_minimo: 10,  precio_unitario: 180 },
  { id: 7, nombre: 'Filtro de Aire',      categoria: 'repuesto',           unidad: 'unidad',  stock_actual: 8,    stock_minimo: 10,  precio_unitario: 220 },
  { id: 8, nombre: 'Liquido de Frenos',   categoria: 'repuesto',           unidad: 'litros',  stock_actual: 15,   stock_minimo: 5,   precio_unitario: 300 },
]

export const VEHICULOS = [
  { id:   1, placa: 'F-001', marca: 'Toyota', modelo: 'Land Cruiser', año: 2020, tipo: 'jeepeta', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id:   2, placa: 'F-002', marca: 'Lexus', modelo: 'Lx-570', año: 2010, tipo: 'jeepeta', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id:   3, placa: 'F-003', marca: 'Toyota', modelo: 'Fortuner', año: 2008, tipo: 'jeepeta', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id:   4, placa: 'F-004', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 2, combustible: 'gasolina', color: '', activo: true },
  { id:   5, placa: 'F-005', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 3, combustible: 'gasolina', color: '', activo: true },
  { id:   6, placa: 'F-006', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 4, combustible: 'gasolina', color: '', activo: true },
  { id:   7, placa: 'F-007', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 5, combustible: 'gasolina', color: '', activo: true },
  { id:   8, placa: 'F-008', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 6, combustible: 'gasolina', color: '', activo: true },
  { id:   9, placa: 'F-009', marca: 'Toyota', modelo: '4 Runner', año: 2016, tipo: 'jeepeta', dependencia_id: 7, combustible: 'gasolina', color: '', activo: true },
  { id:  10, placa: 'F-010', marca: 'Toyota', modelo: '4 Runner', año: 2016, tipo: 'jeepeta', dependencia_id: 8, combustible: 'gasolina', color: '', activo: true },
  { id:  11, placa: 'F-011', marca: 'Toyota', modelo: '4 Runner', año: 2016, tipo: 'jeepeta', dependencia_id: 9, combustible: 'gasolina', color: '', activo: true },
  { id:  12, placa: 'F-012', marca: 'Toyota', modelo: '4 Runner', año: 2016, tipo: 'jeepeta', dependencia_id: 10, combustible: 'gasolina', color: '', activo: true },
  { id:  13, placa: 'F-013', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 11, combustible: 'gasolina', color: '', activo: true },
  { id:  14, placa: 'F-014', marca: 'Toyota', modelo: 'Fortuner', año: 2017, tipo: 'jeepeta', dependencia_id: 12, combustible: 'gasolina', color: '', activo: true },
  { id:  15, placa: 'F-015', marca: 'Toyota', modelo: '4 Runner', año: 2020, tipo: 'jeepeta', dependencia_id: 13, combustible: 'gasolina', color: '', activo: true },
  { id:  16, placa: 'F-016', marca: 'Toyota', modelo: 'Prado', año: 2015, tipo: 'jeepeta', dependencia_id: 14, combustible: 'gasolina', color: '', activo: true },
  { id:  17, placa: 'F-017', marca: 'Toyota', modelo: 'Fortuner', año: 2007, tipo: 'jeepeta', dependencia_id: 15, combustible: 'gasolina', color: '', activo: true },
  { id:  18, placa: 'F-018', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 16, combustible: 'gasolina', color: '', activo: true },
  { id:  19, placa: 'F-019', marca: 'Toyota', modelo: 'Fortuner', año: 2009, tipo: 'jeepeta', dependencia_id: 17, combustible: 'gasolina', color: '', activo: true },
  { id:  20, placa: 'F-020', marca: 'Lexus', modelo: 'Xl-470', año: 2005, tipo: 'jeepeta', dependencia_id: 18, combustible: 'gasolina', color: '', activo: true },
  { id:  21, placa: 'F-021', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 19, combustible: 'gasolina', color: '', activo: true },
  { id:  22, placa: 'F-022', marca: 'Toyota', modelo: 'Corolla', año: 2009, tipo: 'sedan', dependencia_id: 20, combustible: 'gasolina', color: '', activo: true },
  { id:  23, placa: 'F-023', marca: 'Hyundai', modelo: 'Tucson', año: 2011, tipo: 'jeepeta', dependencia_id: 17, combustible: 'gasolina', color: '', activo: true },
  { id:  24, placa: 'F-024', marca: 'Toyota', modelo: 'Hilux', año: 2009, tipo: 'pickup', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  25, placa: 'F-025', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 22, combustible: 'gasolina', color: '', activo: true },
  { id:  26, placa: 'F-026', marca: 'Nissan', modelo: 'Frontier', año: 2009, tipo: 'pickup', dependencia_id: 23, combustible: 'gasolina', color: '', activo: true },
  { id:  27, placa: 'F-027', marca: 'Toyota', modelo: 'Corolla', año: 2009, tipo: 'sedan', dependencia_id: 23, combustible: 'gasolina', color: '', activo: true },
  { id:  28, placa: 'F-028', marca: 'Chevrolet', modelo: 'Colorado', año: 2017, tipo: 'pickup', dependencia_id: 24, combustible: 'gasolina', color: '', activo: true },
  { id:  29, placa: 'F-029', marca: 'Ford', modelo: 'Ranger', año: 2011, tipo: 'otro', dependencia_id: 25, combustible: 'gasolina', color: '', activo: true },
  { id:  30, placa: 'F-030', marca: 'Toyota', modelo: 'Hilux', año: 2008, tipo: 'pickup', dependencia_id: 26, combustible: 'gasolina', color: '', activo: true },
  { id:  31, placa: 'F-031', marca: 'Nissan', modelo: 'Urvan', año: 2010, tipo: 'otro', dependencia_id: 27, combustible: 'gasolina', color: '', activo: true },
  { id:  32, placa: 'F-032', marca: 'Hyundai', modelo: 'Santa Fe', año: 2016, tipo: 'otro', dependencia_id: 27, combustible: 'gasolina', color: '', activo: true },
  { id:  33, placa: 'F-033', marca: 'Toyota', modelo: 'Hilux', año: 2002, tipo: 'otro', dependencia_id: 27, combustible: 'gasolina', color: '', activo: true },
  { id:  34, placa: 'F-034', marca: 'Nissan', modelo: 'Frontier', año: 2009, tipo: 'pickup', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id:  35, placa: 'F-035', marca: 'Mazda', modelo: 'B-2900', año: 1989, tipo: 'pickup', dependencia_id: 29, combustible: 'gasolina', color: '', activo: true },
  { id:  36, placa: 'F-036', marca: 'Toyota', modelo: 'Hilux', año: 2019, tipo: 'pickup', dependencia_id: 30, combustible: 'gasolina', color: '', activo: true },
  { id:  37, placa: 'F-037', marca: 'Toyota', modelo: 'Hiace', año: 2016, tipo: 'microbus', dependencia_id: 31, combustible: 'gasoil', color: '', activo: true },
  { id:  38, placa: 'F-038', marca: 'Toyota', modelo: 'Hiace', año: 2017, tipo: 'microbus', dependencia_id: 32, combustible: 'gasoil', color: '', activo: true },
  { id:  39, placa: 'F-039', marca: 'Toyota', modelo: 'Hilux', año: 2008, tipo: 'otro', dependencia_id: 33, combustible: 'gasolina', color: '', activo: true },
  { id:  40, placa: 'F-040', marca: 'Toyota', modelo: 'Hilux', año: 1997, tipo: 'pickup', dependencia_id: 34, combustible: 'gasolina', color: '', activo: true },
  { id:  41, placa: 'F-041', marca: 'Nissan', modelo: 'Frontier', año: 2003, tipo: 'pickup', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  42, placa: 'F-042', marca: 'Mitsubishi', modelo: 'Fuso', año: 2023, tipo: 'camion', dependencia_id: 33, combustible: 'gasoil', color: '', activo: true },
  { id:  43, placa: 'F-043', marca: 'Mitsubishi', modelo: 'Canter', año: 1993, tipo: 'camion', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id:  44, placa: 'F-044', marca: 'Toyota', modelo: 'Hilux', año: 2010, tipo: 'pickup', dependencia_id: 35, combustible: 'gasolina', color: '', activo: true },
  { id:  45, placa: 'F-045', marca: 'Hyundai', modelo: 'County', año: 2003, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id:  46, placa: 'F-046', marca: 'Hyundai', modelo: 'County (H-1)', año: 2003, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id:  47, placa: 'F-047', marca: 'Mitsubishi', modelo: 'Fuso', año: 2023, tipo: 'microbus', dependencia_id: 22, combustible: 'gasoil', color: '', activo: true },
  { id:  48, placa: 'F-048', marca: 'Hyundai', modelo: 'Tucson', año: 2017, tipo: 'jeepeta', dependencia_id: 36, combustible: 'gasolina', color: '', activo: true },
  { id:  49, placa: 'F-049', marca: 'Toyota', modelo: 'Hilux', año: 2019, tipo: 'pickup', dependencia_id: 9, combustible: 'gasolina', color: '', activo: true },
  { id:  50, placa: 'F-050', marca: 'Hyundai', modelo: 'Volteo', año: 2022, tipo: 'camion', dependencia_id: 37, combustible: 'gasoil', color: '', activo: true },
  { id:  51, placa: 'F-051', marca: 'Toyota', modelo: 'Hilux', año: 2002, tipo: 'pickup', dependencia_id: 8, combustible: 'gasolina', color: '', activo: true },
  { id:  52, placa: 'F-052', marca: 'Mitsubishi', modelo: 'L-200', año: 2016, tipo: 'pickup', dependencia_id: 38, combustible: 'gasolina', color: '', activo: true },
  { id:  53, placa: 'F-053', marca: 'Mitsubishi', modelo: 'L-200', año: 2005, tipo: 'pickup', dependencia_id: 39, combustible: 'gasolina', color: '', activo: true },
  { id:  54, placa: 'F-054', marca: 'Nissan', modelo: 'Frontier', año: 1998, tipo: 'pickup', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id:  55, placa: 'F-055', marca: 'Toyota', modelo: 'Hilux', año: 2010, tipo: 'pickup', dependencia_id: 40, combustible: 'gasolina', color: '', activo: true },
  { id:  56, placa: 'F-056', marca: 'Dongfeng', modelo: 'Garbage', año: 2000, tipo: 'camion', dependencia_id: 41, combustible: 'gasoil', color: '', activo: true },
  { id:  57, placa: 'F-057', marca: 'Toyota', modelo: 'Coaster', año: 2020, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id:  58, placa: 'F-058', marca: 'Toyota', modelo: 'Hilux', año: 2011, tipo: 'pickup', dependencia_id: 42, combustible: 'gasolina', color: '', activo: true },
  { id:  59, placa: 'F-059', marca: 'Toyota', modelo: 'Hiace', año: 2017, tipo: 'microbus', dependencia_id: 12, combustible: 'gasoil', color: '', activo: true },
  { id:  60, placa: 'F-060', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 37, combustible: 'gasolina', color: '', activo: true },
  { id:  61, placa: 'F-061', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 32, combustible: 'gasolina', color: '', activo: true },
  { id:  62, placa: 'F-062', marca: 'Mitsubishi', modelo: 'Fuso', año: 2019, tipo: 'otro', dependencia_id: 43, combustible: 'gasolina', color: '', activo: true },
  { id:  63, placa: 'F-063', marca: 'Mitsubishi', modelo: 'Canter', año: 2015, tipo: 'camion', dependencia_id: 24, combustible: 'gasoil', color: '', activo: true },
  { id:  64, placa: 'F-064', marca: 'Toyota', modelo: 'Hiace', año: 2019, tipo: 'otro', dependencia_id: 44, combustible: 'gasolina', color: '', activo: true },
  { id:  65, placa: 'F-065', marca: 'Suzuki', modelo: 'Apb', año: 2007, tipo: 'jeepeta', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id:  66, placa: 'F-066', marca: 'Toyota', modelo: 'Corolla', año: 2009, tipo: 'sedan', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id:  67, placa: 'F-067', marca: 'Hyundai', modelo: 'Universe', año: 2009, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id:  68, placa: 'F-068', marca: 'Hyundai', modelo: 'Volteo', año: 2022, tipo: 'camion', dependencia_id: 41, combustible: 'gasoil', color: '', activo: true },
  { id:  69, placa: 'F-069', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 45, combustible: 'gasolina', color: '', activo: true },
  { id:  70, placa: 'F-070', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 10, combustible: 'gasolina', color: '', activo: true },
  { id:  71, placa: 'F-071', marca: 'Nissan', modelo: 'Frontier', año: 2012, tipo: 'pickup', dependencia_id: 46, combustible: 'gasolina', color: '', activo: true },
  { id:  72, placa: 'F-072', marca: 'Nissan', modelo: 'Urvan', año: 2010, tipo: 'microbus', dependencia_id: 47, combustible: 'gasoil', color: '', activo: true },
  { id:  73, placa: 'F-073', marca: 'Hyundai', modelo: 'H-1 Tq', año: 2011, tipo: 'microbus', dependencia_id: 48, combustible: 'gasoil', color: '', activo: true },
  { id:  74, placa: 'F-074', marca: 'Yamaha', modelo: '***', año: 2007, tipo: 'motocicleta', dependencia_id: 48, combustible: 'gasolina', color: '', activo: true },
  { id:  75, placa: 'F-075', marca: 'Toyota', modelo: 'Hilux', año: 2000, tipo: 'pickup', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id:  76, placa: 'F-076', marca: 'Toyota', modelo: 'Hilux', año: 2010, tipo: 'pickup', dependencia_id: 49, combustible: 'gasolina', color: '', activo: true },
  { id:  77, placa: 'F-077', marca: 'Loncin', modelo: 'Pruss200', año: 2018, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  78, placa: 'F-078', marca: 'Toyota', modelo: 'Hiace', año: 2018, tipo: 'microbus', dependencia_id: 50, combustible: 'gasoil', color: '', activo: true },
  { id:  79, placa: 'F-079', marca: 'Toyota', modelo: 'Hiace', año: 2012, tipo: 'microbus', dependencia_id: 51, combustible: 'gasoil', color: '', activo: true },
  { id:  80, placa: 'F-080', marca: 'Nissan', modelo: '2-D', año: 1998, tipo: 'pickup', dependencia_id: 52, combustible: 'gasolina', color: '', activo: true },
  { id:  81, placa: 'F-081', marca: 'Toyota', modelo: 'Coaster', año: 2011, tipo: 'microbus', dependencia_id: 53, combustible: 'gasoil', color: '', activo: true },
  { id:  82, placa: 'F-082', marca: 'Nissan', modelo: 'Turistar', año: 2016, tipo: 'microbus', dependencia_id: 54, combustible: 'gasoil', color: '', activo: true },
  { id:  83, placa: 'F-083', marca: 'Loncin', modelo: 'Pruss200', año: 2018, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  84, placa: 'F-084', marca: 'Loncin', modelo: 'Pruss200', año: 2018, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  85, placa: 'F-085', marca: 'Toyota', modelo: 'Hiace', año: 2020, tipo: 'otro', dependencia_id: 51, combustible: 'gasolina', color: '', activo: true },
  { id:  86, placa: 'F-086', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 55, combustible: 'gasolina', color: '', activo: true },
  { id:  87, placa: 'F-087', marca: 'Loncin', modelo: 'Pruss200', año: 2018, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  88, placa: 'F-088', marca: 'Loncin', modelo: 'Pruss200', año: 2018, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  89, placa: 'F-089', marca: 'Toyota', modelo: 'Hilux', año: 2009, tipo: 'pickup', dependencia_id: 56, combustible: 'gasolina', color: '', activo: true },
  { id:  90, placa: 'F-090', marca: 'Toyota', modelo: 'Coaster', año: 2011, tipo: 'microbus', dependencia_id: 53, combustible: 'gasoil', color: '', activo: true },
  { id:  91, placa: 'F-091', marca: 'Mitsubishi', modelo: 'L-200', año: 2015, tipo: 'pickup', dependencia_id: 57, combustible: 'gasolina', color: '', activo: true },
  { id:  92, placa: 'F-092', marca: 'Yamaha', modelo: 'Crux-S', año: 2014, tipo: 'motocicleta', dependencia_id: 23, combustible: 'gasolina', color: '', activo: true },
  { id:  93, placa: 'F-093', marca: 'Loncin', modelo: 'Pruss 200', año: 2020, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id:  94, placa: 'F-094', marca: 'Hyundai', modelo: 'Elantra', año: 2009, tipo: 'sedan', dependencia_id: 58, combustible: 'gasolina', color: '', activo: true },
  { id:  95, placa: 'F-095', marca: 'Toyota', modelo: 'Corolla', año: 2001, tipo: 'sedan', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id:  96, placa: 'F-096', marca: 'Mitsubishi', modelo: 'Canter', año: 2016, tipo: 'camion', dependencia_id: 56, combustible: 'gasoil', color: '', activo: true },
  { id:  97, placa: 'F-097', marca: 'Mitsubishi', modelo: 'Fuso Rosa', año: 2005, tipo: 'microbus', dependencia_id: 59, combustible: 'gasoil', color: '', activo: true },
  { id:  98, placa: 'F-098', marca: 'Hyundai', modelo: 'Country', año: 2019, tipo: 'autobus', dependencia_id: 56, combustible: 'gasoil', color: '', activo: true },
  { id:  99, placa: 'F-099', marca: 'Hyundai', modelo: 'Santa Fe', año: 2008, tipo: 'jeepeta', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 100, placa: 'F-100', marca: 'Dongfeng', modelo: 'Garbage', año: 2024, tipo: 'camion', dependencia_id: 41, combustible: 'gasoil', color: '', activo: true },
  { id: 101, placa: 'F-101', marca: 'Toyota', modelo: 'Coaster', año: 2020, tipo: 'microbus', dependencia_id: 60, combustible: 'gasoil', color: '', activo: true },
  { id: 102, placa: 'F-102', marca: 'Toyota', modelo: 'Hiace', año: 2009, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 103, placa: 'F-103', marca: 'Ford', modelo: 'Ranger', año: 2011, tipo: 'pickup', dependencia_id: 12, combustible: 'gasolina', color: '', activo: true },
  { id: 104, placa: 'F-104', marca: 'Hyundai', modelo: 'Universe', año: 2020, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 105, placa: 'F-105', marca: 'Scania', modelo: 'Comil', año: 2013, tipo: 'otro', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 106, placa: 'F-106', marca: 'Toyota', modelo: 'Hiace', año: 2020, tipo: 'microbus', dependencia_id: 61, combustible: 'gasoil', color: '', activo: true },
  { id: 107, placa: 'F-107', marca: 'Toyota', modelo: 'Fortuner', año: 2008, tipo: 'jeepeta', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id: 108, placa: 'F-108', marca: 'Toyota', modelo: 'Coaster', año: 2016, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 109, placa: 'F-109', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 13, combustible: 'gasolina', color: '', activo: true },
  { id: 110, placa: 'F-110', marca: 'Mitsubishi', modelo: 'L-200', año: 2013, tipo: 'pickup', dependencia_id: 62, combustible: 'gasolina', color: '', activo: true },
  { id: 111, placa: 'F-111', marca: 'Yamaha', modelo: 'Ydrax2', año: 2011, tipo: 'otro', dependencia_id: 29, combustible: 'gasolina', color: '', activo: true },
  { id: 112, placa: 'F-112', marca: 'Toyota', modelo: 'Hiace', año: 2019, tipo: 'otro', dependencia_id: 57, combustible: 'gasolina', color: '', activo: true },
  { id: 113, placa: 'F-113', marca: 'Hyundai', modelo: 'Santa Fe', año: 2014, tipo: 'otro', dependencia_id: 43, combustible: 'gasolina', color: '', activo: true },
  { id: 114, placa: 'F-114', marca: 'Hyundai', modelo: 'Tucson', año: 2011, tipo: 'otro', dependencia_id: 62, combustible: 'gasolina', color: '', activo: true },
  { id: 115, placa: 'F-115', marca: 'Hyundai', modelo: 'County', año: 2002, tipo: 'otro', dependencia_id: 57, combustible: 'gasolina', color: '', activo: true },
  { id: 116, placa: 'F-116', marca: 'Mitsubishi', modelo: 'Fuso Rosa', año: 2023, tipo: 'microbus', dependencia_id: 57, combustible: 'gasoil', color: '', activo: true },
  { id: 117, placa: 'F-117', marca: 'Daihatsu', modelo: 'Delta', año: 2005, tipo: 'camion', dependencia_id: 63, combustible: 'gasoil', color: '', activo: true },
  { id: 118, placa: 'F-118', marca: 'Hyundai', modelo: 'Space', año: 2002, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 119, placa: 'F-119', marca: 'Toyota', modelo: 'Fortuner', año: 2015, tipo: 'otro', dependencia_id: 59, combustible: 'gasolina', color: '', activo: true },
  { id: 120, placa: 'F-120', marca: 'Nissan', modelo: 'Frontier', año: 2007, tipo: 'otro', dependencia_id: 59, combustible: 'gasolina', color: '', activo: true },
  { id: 121, placa: 'F-121', marca: 'Toyota', modelo: '4Runner', año: 2019, tipo: 'jeepeta', dependencia_id: 56, combustible: 'gasolina', color: '', activo: true },
  { id: 122, placa: 'F-122', marca: 'Toyota', modelo: 'Coaster', año: 2002, tipo: 'microbus', dependencia_id: 56, combustible: 'gasoil', color: '', activo: true },
  { id: 123, placa: 'F-123', marca: 'Mitsubishi', modelo: 'Fuso Rosa', año: 2024, tipo: 'microbus', dependencia_id: 56, combustible: 'gasoil', color: '', activo: true },
  { id: 124, placa: 'F-124', marca: 'Toyota', modelo: 'Prado', año: 2007, tipo: 'jeepeta', dependencia_id: 2, combustible: 'gasolina', color: '', activo: true },
  { id: 125, placa: 'F-125', marca: 'Hyundai', modelo: 'Space', año: 2003, tipo: 'otro', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 126, placa: 'F-126', marca: 'Toyota', modelo: 'Hilux', año: 2019, tipo: 'pickup', dependencia_id: 53, combustible: 'gasolina', color: '', activo: true },
  { id: 127, placa: 'F-127', marca: 'Nissan', modelo: 'Frontier', año: 2007, tipo: 'pickup', dependencia_id: 64, combustible: 'gasolina', color: '', activo: true },
  { id: 128, placa: 'F-128', marca: 'Nissan', modelo: 'Frontier', año: 2011, tipo: 'pickup', dependencia_id: 65, combustible: 'gasolina', color: '', activo: true },
  { id: 129, placa: 'F-129', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 130, placa: 'F-130', marca: 'Yamaha', modelo: '', año: 2013, tipo: 'motocicleta', dependencia_id: 41, combustible: 'gasolina', color: '', activo: true },
  { id: 131, placa: 'F-132', marca: 'Mitsubishi', modelo: 'Nativa', año: 2015, tipo: 'jeepeta', dependencia_id: 66, combustible: 'gasolina', color: '', activo: true },
  { id: 132, placa: 'F-133', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 67, combustible: 'gasolina', color: '', activo: true },
  { id: 133, placa: 'F-134', marca: 'Toyota', modelo: 'Prado 4X4', año: 2007, tipo: 'jeepeta', dependencia_id: 68, combustible: 'gasolina', color: '', activo: true },
  { id: 134, placa: 'F-135', marca: 'Chevrolet', modelo: 'Sonic', año: 2013, tipo: 'sedan', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 135, placa: 'F-136', marca: 'Nissan', modelo: 'Frontier', año: 2005, tipo: 'pickup', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 136, placa: 'F-137', marca: 'Nissan', modelo: 'Frontier', año: 2009, tipo: 'pickup', dependencia_id: 14, combustible: 'gasolina', color: '', activo: true },
  { id: 137, placa: 'F-138', marca: 'Nissan', modelo: 'Frontier', año: 2003, tipo: 'pickup', dependencia_id: 69, combustible: 'gasolina', color: '', activo: true },
  { id: 138, placa: 'F-139', marca: 'Toyota', modelo: 'Hiace', año: 2020, tipo: 'microbus', dependencia_id: 70, combustible: 'gasoil', color: '', activo: true },
  { id: 139, placa: 'F-140', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 71, combustible: 'gasolina', color: '', activo: true },
  { id: 140, placa: 'F-141', marca: 'Toyota', modelo: 'Hilux', año: 2017, tipo: 'pickup', dependencia_id: 33, combustible: 'gasolina', color: '', activo: true },
  { id: 141, placa: 'F-142', marca: 'Toyota', modelo: 'Coaster', año: 2009, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 142, placa: 'F-143', marca: 'Renaurt', modelo: 'Kangoo', año: 2003, tipo: 'otro', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 143, placa: 'F-144', marca: 'Toyota', modelo: 'Coaster', año: 2010, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 144, placa: 'F-145', marca: 'Yamaha', modelo: '', año: 2017, tipo: 'motocicleta', dependencia_id: 72, combustible: 'gasolina', color: '', activo: true },
  { id: 145, placa: 'F-146', marca: 'Toyota', modelo: 'Prado', año: 2007, tipo: 'jeepeta', dependencia_id: 73, combustible: 'gasolina', color: '', activo: true },
  { id: 146, placa: 'F-147', marca: 'Hyundai', modelo: 'Universe', año: 2009, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 147, placa: 'F-148', marca: 'Toyota', modelo: 'Hiace', año: 2012, tipo: 'microbus', dependencia_id: 43, combustible: 'gasoil', color: '', activo: true },
  { id: 148, placa: 'F-149', marca: 'Hyundai', modelo: 'Universe', año: 2020, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 149, placa: 'F-150', marca: 'Ford', modelo: 'Ranger', año: 2011, tipo: 'pickup', dependencia_id: 74, combustible: 'gasolina', color: '', activo: true },
  { id: 150, placa: 'F-151', marca: 'Scania', modelo: 'Comil', año: 2010, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 151, placa: 'F-152', marca: 'Loncin', modelo: 'Ex-200', año: 2024, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id: 152, placa: 'F-153', marca: 'Hyundai', modelo: 'County', año: 2013, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 153, placa: 'F-154', marca: 'Nissan', modelo: 'Frontier', año: 2005, tipo: 'pickup', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 154, placa: 'F-155', marca: 'Mitsubichi', modelo: 'L-200', año: 2016, tipo: 'pickup', dependencia_id: 32, combustible: 'gasolina', color: '', activo: true },
  { id: 155, placa: 'F-156', marca: 'Hyundai', modelo: 'County', año: 2003, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 156, placa: 'F-157', marca: 'Hyundai', modelo: 'Ambulancia', año: 2012, tipo: 'microbus', dependencia_id: 19, combustible: 'gasoil', color: '', activo: true },
  { id: 157, placa: 'F-158', marca: 'Yamaha', modelo: 'Jan', año: 2024, tipo: 'motocicleta', dependencia_id: 75, combustible: 'gasolina', color: '', activo: true },
  { id: 158, placa: 'F-159', marca: 'Loncin', modelo: 'Ex-200', año: 2024, tipo: 'motocicleta', dependencia_id: 21, combustible: 'gasolina', color: '', activo: true },
  { id: 159, placa: 'F-160', marca: 'Toyota', modelo: 'Hilux', año: 2009, tipo: 'pickup', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 160, placa: 'F-161', marca: 'Nissan', modelo: 'Turister', año: 2018, tipo: 'microbus', dependencia_id: 76, combustible: 'gasoil', color: '', activo: true },
  { id: 161, placa: 'F-162', marca: 'Nissan', modelo: 'D-22', año: 2003, tipo: 'pickup', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 162, placa: 'F-163', marca: 'Toyota', modelo: 'Coaster', año: 2008, tipo: 'microbus', dependencia_id: 77, combustible: 'gasoil', color: '', activo: true },
  { id: 163, placa: 'F-164', marca: 'Mitsubishi', modelo: 'Eclipse Cross', año: 2024, tipo: 'otro', dependencia_id: 54, combustible: 'gasolina', color: '', activo: true },
  { id: 164, placa: 'F-165', marca: 'Mitsubishi', modelo: 'Rosa', año: 2025, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 165, placa: 'F-166', marca: 'Mitsubishi', modelo: 'Rosa', año: 2025, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 166, placa: 'F-167', marca: 'Nissan', modelo: 'Urvan', año: 2010, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 167, placa: 'F-168', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 78, combustible: 'gasolina', color: '', activo: true },
  { id: 168, placa: 'F-169', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 79, combustible: 'gasolina', color: '', activo: true },
  { id: 169, placa: 'F-170', marca: 'Toyota', modelo: 'Fortuner', año: 2023, tipo: 'otro', dependencia_id: 1, combustible: 'gasolina', color: '', activo: true },
  { id: 170, placa: 'F-171', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 80, combustible: 'gasolina', color: '', activo: true },
  { id: 171, placa: 'F-172', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 81, combustible: 'gasolina', color: '', activo: true },
  { id: 172, placa: 'F-173', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 173, placa: 'F-174', marca: 'Toyota', modelo: 'Hilux', año: 2023, tipo: 'pickup', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 174, placa: 'F-175', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 175, placa: 'F-176', marca: 'Ford', modelo: 'Ranger', año: 2011, tipo: 'pickup', dependencia_id: 51, combustible: 'gasolina', color: '', activo: true },
  { id: 176, placa: 'F-177', marca: 'Toyota', modelo: 'Hilux', año: 2020, tipo: 'pickup', dependencia_id: 82, combustible: 'gasolina', color: '', activo: true },
  { id: 177, placa: 'F-178', marca: 'Ford', modelo: 'Ranger', año: 2011, tipo: 'pickup', dependencia_id: 83, combustible: 'gasolina', color: '', activo: true },
  { id: 178, placa: 'F-179', marca: 'Toyota', modelo: 'Corolla', año: 2009, tipo: 'sedan', dependencia_id: 37, combustible: 'gasolina', color: '', activo: true },
  { id: 179, placa: 'F-180', marca: 'Nissan', modelo: 'D-22', año: 2003, tipo: 'pickup', dependencia_id: 84, combustible: 'gasolina', color: '', activo: true },
  { id: 180, placa: 'F-181', marca: 'Toyota', modelo: 'Prado', año: 2007, tipo: 'jeepeta', dependencia_id: 85, combustible: 'gasolina', color: '', activo: true },
  { id: 181, placa: 'F-182', marca: 'Daihatsu', modelo: 'Delta', año: 2008, tipo: 'camion', dependencia_id: 41, combustible: 'gasoil', color: '', activo: true },
  { id: 182, placa: 'F-183', marca: 'Nissan', modelo: 'Touristar', año: 2018, tipo: 'microbus', dependencia_id: 44, combustible: 'gasoil', color: '', activo: true },
  { id: 183, placa: 'F-184', marca: 'Toyota', modelo: '4Runner', año: 2019, tipo: 'jeepeta', dependencia_id: 60, combustible: 'gasolina', color: '', activo: true },
  { id: 184, placa: 'F-185', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 60, combustible: 'gasolina', color: '', activo: true },
  { id: 185, placa: 'F-186', marca: 'Toyota', modelo: 'Coaster', año: 2023, tipo: 'microbus', dependencia_id: 25, combustible: 'gasoil', color: '', activo: true },
  { id: 186, placa: 'F-187', marca: 'Toyota', modelo: 'Hilux', año: 2011, tipo: 'pickup', dependencia_id: 43, combustible: 'gasolina', color: '', activo: true },
  { id: 187, placa: 'F-188', marca: 'Isuzu', modelo: 'Npr', año: 2020, tipo: 'camion', dependencia_id: 76, combustible: 'gasoil', color: '', activo: true },
  { id: 188, placa: 'F-189', marca: 'Toyota', modelo: 'Hilux', año: 2019, tipo: 'pickup', dependencia_id: 76, combustible: 'gasolina', color: '', activo: true },
  { id: 189, placa: 'F-190', marca: 'Toyota', modelo: 'Fortuner', año: 2013, tipo: 'jeepeta', dependencia_id: 86, combustible: 'gasolina', color: '', activo: true },
  { id: 190, placa: 'F-191', marca: 'Yamaha', modelo: 'Crux-S', año: 2007, tipo: 'motocicleta', dependencia_id: 87, combustible: 'gasolina', color: '', activo: true },
  { id: 191, placa: 'F-192', marca: 'Toyota', modelo: 'Prado', año: 2007, tipo: 'jeepeta', dependencia_id: 88, combustible: 'gasolina', color: '', activo: true },
  { id: 192, placa: 'F-193', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 193, placa: 'F-194', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 194, placa: 'F-195', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 195, placa: 'F-196', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 196, placa: 'F-197', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 197, placa: 'F-198', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 198, placa: 'F-199', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 199, placa: 'F-200', marca: 'Toyota', modelo: 'Coaster', año: 2024, tipo: 'microbus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 200, placa: 'F-201', marca: 'Hyundai', modelo: 'Santa Fe', año: 2000, tipo: 'jeepeta', dependencia_id: 28, combustible: 'gasolina', color: '', activo: true },
  { id: 201, placa: 'F-202', marca: 'Toyota', modelo: 'Hilux', año: 2024, tipo: 'pickup', dependencia_id: 89, combustible: 'gasolina', color: '', activo: true },
  { id: 202, placa: 'F-204', marca: 'Hyundai', modelo: 'H-1', año: 2011, tipo: 'microbus', dependencia_id: 19, combustible: 'gasoil', color: '', activo: true },
  { id: 203, placa: 'F-205', marca: 'Hyundai', modelo: 'Universe', año: 2000, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 204, placa: 'F-206', marca: 'Hyundai', modelo: 'Universe', año: 2000, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 205, placa: 'F-207', marca: 'Hyundai', modelo: 'Universe', año: 2000, tipo: 'autobus', dependencia_id: 28, combustible: 'gasoil', color: '', activo: true },
  { id: 206, placa: 'F-208', marca: 'Toyota', modelo: 'Hiace', año: 2018, tipo: 'microbus', dependencia_id: 77, combustible: 'gasoil', color: '', activo: true },
  { id: 207, placa: 'F-209', marca: 'Toyota', modelo: 'Hilux', año: 2000, tipo: 'pickup', dependencia_id: 41, combustible: 'gasolina', color: '', activo: true },
  { id: 208, placa: 'F-210', marca: 'Toyota', modelo: 'Hilux', año: 2022, tipo: 'pickup', dependencia_id: 25, combustible: 'gasolina', color: '', activo: true },
  { id: 209, placa: 'F-211', marca: 'Toyota', modelo: 'Fortuner', año: 2017, tipo: 'jeepeta', dependencia_id: 77, combustible: 'gasolina', color: '', activo: true },
]

export const DESPACHOS = [
  { id: 1,  vehiculo_id: 1,  producto_id: 1, cantidad: 10, unidad: 'galones', despachado_por: 2, solicitado_por: 'Pedro Martinez',  cedula_receptor: '001-0000001-1', km_vehiculo: 45230, fecha_despacho: '2026-03-15T08:30:00', observaciones: null },
  { id: 2,  vehiculo_id: 3,  producto_id: 3, cantidad: 4,  unidad: 'cuartos', despachado_por: 2, solicitado_por: 'Luis Garcia',     cedula_receptor: null,            km_vehiculo: 32100, fecha_despacho: '2026-03-15T09:15:00', observaciones: 'Cambio de aceite' },
  { id: 3,  vehiculo_id: 2,  producto_id: 2, cantidad: 15, unidad: 'galones', despachado_por: 2, solicitado_por: 'Carlos Diaz',     cedula_receptor: '001-0000003-3', km_vehiculo: 78900, fecha_despacho: '2026-03-15T10:00:00', observaciones: null },
  { id: 4,  vehiculo_id: 4,  producto_id: 4, cantidad: 6,  unidad: 'cuartos', despachado_por: 2, solicitado_por: 'Jose Ramirez',    cedula_receptor: null,            km_vehiculo: 55400, fecha_despacho: '2026-03-14T08:00:00', observaciones: null },
  { id: 5,  vehiculo_id: 1,  producto_id: 1, cantidad: 8,  unidad: 'galones', despachado_por: 2, solicitado_por: 'Pedro Martinez',  cedula_receptor: '001-0000001-1', km_vehiculo: 45190, fecha_despacho: '2026-03-14T14:00:00', observaciones: null },
  { id: 6,  vehiculo_id: 5,  producto_id: 1, cantidad: 2,  unidad: 'galones', despachado_por: 2, solicitado_por: 'Ana Sanchez',     cedula_receptor: null,            km_vehiculo: 12000, fecha_despacho: '2026-03-13T07:30:00', observaciones: null },
  { id: 7,  vehiculo_id: 6,  producto_id: 2, cantidad: 20, unidad: 'galones', despachado_por: 2, solicitado_por: 'Roberto Nunez',   cedula_receptor: '001-0000007-7', km_vehiculo: 90200, fecha_despacho: '2026-03-13T11:00:00', observaciones: null },
  { id: 8,  vehiculo_id: 3,  producto_id: 6, cantidad: 1,  unidad: 'unidad',  despachado_por: 2, solicitado_por: 'Luis Garcia',     cedula_receptor: null,            km_vehiculo: 32150, fecha_despacho: '2026-03-12T09:00:00', observaciones: 'Filtro danado' },
  { id: 9,  vehiculo_id: 2,  producto_id: 5, cantidad: 4,  unidad: 'cuartos', despachado_por: 2, solicitado_por: 'Carlos Diaz',     cedula_receptor: '001-0000003-3', km_vehiculo: 78800, fecha_despacho: '2026-03-11T10:30:00', observaciones: null },
  { id: 10, vehiculo_id: 4,  producto_id: 2, cantidad: 12, unidad: 'galones', despachado_por: 2, solicitado_por: 'Jose Ramirez',    cedula_receptor: null,            km_vehiculo: 55350, fecha_despacho: '2026-03-10T08:45:00', observaciones: null },
]

// Consumo ultimos 7 dias para grafica del dashboard
export const CONSUMO_7DIAS = [
  { fecha: '09/03', gasolina: 18, gasoil: 25 },
  { fecha: '10/03', gasolina: 22, gasoil: 12 },
  { fecha: '11/03', gasolina: 15, gasoil: 20 },
  { fecha: '12/03', gasolina: 30, gasoil: 15 },
  { fecha: '13/03', gasolina: 12, gasoil: 35 },
  { fecha: '14/03', gasolina: 18, gasoil: 15 },
  { fecha: '15/03', gasolina: 20, gasoil: 15 },
]
